# Generated by Django 2.2.7 on 2019-12-17 14:46

from django.db import migrations, models
import django.db.models.deletion
import electro_shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('electro_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название бренда')),
                ('slug', models.SlugField(verbose_name='Альтернативное название')),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнд',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(verbose_name='Альтернативное название')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('price', models.PositiveIntegerField(verbose_name='Цена товара')),
                ('image', models.ImageField(upload_to=electro_shop.models.image_folder, verbose_name='Фото товара')),
                ('available', models.BooleanField(default=True, verbose_name='Товар в наличии')),
                ('sale', models.BooleanField(blank=True, default=False, verbose_name='Товар участвует в акции')),
                ('sale_percent', models.IntegerField(blank=True, verbose_name='Процент скидки')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electro_shop.Brand', verbose_name='Брэнд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electro_shop.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
