# Generated by Django 2.2.7 on 2019-12-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro_shop', '0004_auto_20191227_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Название'),
        ),
    ]
